services:
    App\Service\Infrastructure\Persistence\Doctrine\DoctrineServiceRepository: ~

    App\Service\Domain\ServiceRepositoryInterface:
        alias: App\Service\Infrastructure\Persistence\Doctrine\DoctrineServiceRepository